AllCops:
  #Include gemspec and Rakefile
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - Rakefile
    - config.ru
  Exclude:
    - 'vendor/**/*'
    - 'spec/**/*'
    - 'db/*.rb'
    - db/schema.rb
  
  Metrics/LineLength:
    Max: 100

  Metrics/MethodLength:
    Max: 15

  Metrics/AbcSize:
    Max: 20

  Style/StringLiterals:
    Enabled: false
  
  EnforcedStyle: double_quotes